import React, {useState, useEffect, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import '@fontsource/inter/400.css';import '@fontsource/inter/500.css';import '@fontsource/inter/600.css';import '@fontsource/inter/700.css';import '@fontsource/manrope/500.css';
import './style.css';
type Page='home'|'prepare'|'summary'|'bleeding'|'symptoms'|'details';
type Entry={id:number,date:string,pad:string,flow:number,symptoms:{name:string,level:number,selected:boolean}[],notes:string,medications:string[]};
const lorem='Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
const asset=(page:string,name:string)=>`/assets/${page}-${name}.svg`;
function Icon({page='home',name,...props}:{page?:string,name:string}&React.ImgHTMLAttributes<HTMLImageElement>){return <img src={asset(page,name)} alt="" {...props}/>}
function App(){
 const [page,setPage]=useState<Page>('home'),[day,setDay]=useState(0),[pad,setPad]=useState('Extra-Long Pad'),[flow,setFlow]=useState(1),[notes,setNotes]=useState('');
 const [symptoms,setSymptoms]=useState([{name:'Headache',level:3,selected:false},{name:'Cramps',level:3,selected:true},{name:'Fatigue',level:3,selected:true},{name:'Headache',level:3,selected:false},{name:'Headache',level:3,selected:false}]);
 const [meds,setMeds]=useState([{name:'Iron supplement',selected:true},{name:'Vitamin D',selected:true},{name:'Ashwagandha Gummy',selected:false}]);
 const [entries,setEntries]=useState<Entry[]>(()=>{try {const x=JSON.parse(localStorage.getItem('care-entries')||'[]');return Array.isArray(x)?x:[]}catch{return []}});
 const [modal,setModal]=useState<{title:string,body:string}|null>(null),[adding,setAdding]=useState<'symptom'|'medication'|null>(null),[newName,setNewName]=useState(''),[period,setPeriod]=useState('Past Summaries');
 const [today]=useState(()=>{const date=new Date();date.setHours(0,0,0,0);return date});
 const dateAt=(offset:number)=>{const date=new Date(today);date.setDate(date.getDate()+offset);return date};
 const selectedDate=dateAt(day);
 const dateHeading=selectedDate.toLocaleDateString('en-US',{month:'long',day:'numeric',...(selectedDate.getFullYear()!==today.getFullYear()?{year:'numeric' as const}:{})}).toUpperCase();
 const dates=Array.from({length:369},(_,index)=>({offset:index-365,date:dateAt(index-365)}));
 const calendar=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(page==='home'&&calendar.current){const row=calendar.current;const todayButton=row.querySelector<HTMLElement>('[aria-current="date"]');if(todayButton)row.scrollTo({left:todayButton.offsetLeft-(row.clientWidth-todayButton.offsetWidth)/2,behavior:"instant"})}},[page]);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(modal||adding)dialog.current?.showModal();else dialog.current?.close()},[modal,adding]);
 function go(p:Page){setPage(p);window.scrollTo({top:0})}
 function save(){const entry:Entry={id:Date.now(),date:selectedDate.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}).toUpperCase(),pad,flow,symptoms:symptoms.filter(s=>s.selected),notes,medications:meds.filter(m=>m.selected).map(m=>m.name)};const next=[entry,...entries];try{localStorage.setItem('care-entries',JSON.stringify(next));setEntries(next);go('home')}catch{setModal({title:'Unable to save',body:'Your browser storage is unavailable. Your form is still here; please try again.'})}}
 const book=()=>setModal({title:'Book Appointment',body:'Dr James Tan · Riverway Family Clinic · Est. S$70–100. This is a prototype: no appointment has been booked.'});
 function Chat({home=false}:{home?:boolean}){const [message,setMessage]=useState('');return <div className="chat"><div className="bubble"><Icon page={page} name="imgIconSpark"/>{home?'Anything to help today ?':'Need other help ?'}</div><form className="reply" onSubmit={e=>{e.preventDefault();if(message.trim()){setModal({title:'Care companion',body:'Your message: '+message+'\n\nThis prototype demonstrates the conversation interface. A live AI assistant is not connected.'});setMessage('')}}}><input aria-label="Message the care companion" value={message} onChange={e=>setMessage(e.target.value)} placeholder="|"/><button aria-label="Send message"><Icon page={page} name="imgVuesaxLinearDirectRight"/></button></form></div>}
 function Heading({children}:{children:React.ReactNode}){return <h2 className="ai-heading"><Icon page={page} name="imgContainer"/>{children}</h2>}
 const step=['bleeding','symptoms','details'].indexOf(page);
 return <div className={`app ${page}`}><header className="status" aria-hidden="true"><b>9:41</b><span className="island"/><span className="status-symbols"><span className="signal"><i/><i/><i/><i/></span><span className="wifi">◓</span><span className="battery"/></span></header>
 {page==='home'?<><h1 className="month">{dateHeading}</h1><div className="calendar" ref={calendar} tabIndex={0} role="region" aria-label="Scroll dates; the next three days are preview only"><div className="date-strip">{dates.map(({date,offset})=><button key={offset} className={`date ${day===offset?'selected':''}`} disabled={offset>0} title={offset>0?'Future date — entries are not available':undefined} onClick={()=>setDay(Math.min(0,offset))} aria-label={`${offset===0?'Today, ':''}${date.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}`} aria-pressed={day===offset} aria-current={offset===0?'date':undefined}><span>{offset===0?'TODAY':date.toLocaleDateString('en-US',{weekday:'short'})}</span><span className="date-circle"><Icon name={day===offset?'imgEllipse3':'imgEllipse4'}/><span>{date.getDate()}</span></span></button>)}</div></div><main className="home-content"><section className="care-card"><Heading>AI SAFETY &amp; CARE</Heading><p className="care-text">You recorded fatigue more often on<br/>Tuesday afternoons over the past three<br className="wide-break"/> weeks. Ensuring adequate hydration and short rest periods might be beneficial.</p><div className="frequency"><p>Fatigue Frequency (Last 7 Days)</p><div className="hearts">{['W','T','F','S','S','M','T'].map((d,i)=><div key={i}><Icon name={i===0||i===3||i===5?'imgVuesaxLinearHeart2':'imgVuesaxLinearHeart1'}/><span>{d}</span></div>)}</div></div><Chat home/></section><button className="add-entry" onClick={()=>go('bleeding')}><span className="add-circle"><Icon name="imgEllipse104"/><Icon className="plus" name="imgVuesaxLinearAdd"/></span><strong>{day===0?'Add today’s entry':`Add entry for ${selectedDate.toLocaleDateString('en-GB',{day:'numeric',month:'short'})}`}</strong></button><section className="recent"><h2>Recent Entries</h2>{entries.length?entries.map(e=><button key={e.id} className="entry-card" onClick={()=>setModal({title:e.date,body:`${e.pad} · ${['Light','Medium','Heavy'][e.flow]} flow\n${e.symptoms.map(s=>`${s.name}: ${s.level}/5`).join(', ')}\n${e.notes}\n${e.medications.join(', ')}`})}><span><strong>{e.date}</strong><small>{e.notes||e.symptoms.map(s=>s.name).join(', ')||'Daily entry'}</small></span><span className="entry-thumb"/></button>):[0,1].map(i=><button className="entry-card" key={i} onClick={()=>setModal({title:'Entry Name',body:'Description (one sentence / word) — this is the placeholder entry supplied in the Figma design.'})}><span><strong>Entry Name</strong><small>Description (one sentence / word)</small></span><span className="entry-thumb"/></button>)}</section></main></>:null}
 {page==='prepare'&&<main className="content prepare-content"><h1>PREPARE</h1><Heading>AI SUGGESTIONS</Heading>{[0,1].map(i=><section className="doctor-card card" key={i}><div className="doctor"><span className="avatar">JT</span><div><h3>Dr James Tan</h3><p>Riverway Family Clinic</p><p className="purple">★ 4.8 · 64 reviews</p></div></div><details><summary><span>Est. S$70–100</span><span>Details <Icon page="prepare" name="imgVuesaxLinearArrowDown"/></span></summary><p>Dr James Tan · Riverway Family Clinic<br/>★ 4.8 · 64 reviews</p></details><p className="doctor-description">{lorem}</p><button className="primary compact" onClick={book}>Book Appointment</button></section>)}<Chat/></main>}
 {page==='summary'&&<main className="content summary-content"><div className="summary-heading"><h1>SYMPTOM SUMMARY</h1><select aria-label="Summary period" value={period} onChange={e=>setPeriod(e.target.value)}><option>Past Summaries</option><option>Today</option><option>All entries</option></select></div>{(entries.length?entries:period==='Today'?[]:[null,null,null]).map((e,i)=><section className="card evidence" key={e?.id||i}><h3>{e?.date||'3 OCTOBER'}</h3><div className="evidence-columns"><div><h4>SUMMARY OF THE DAY</h4><p>{e?`${['Light','Medium','Heavy'][e.flow]} flow. ${e.symptoms.map(s=>`${s.name} ${s.level}/5`).join(', ')}.`:lorem}</p></div><button className="source" onClick={()=>setModal({title:'FROM YOUR ENTRY',body:e?.notes||lorem})}><h4>FROM YOUR ENTRY</h4><p>“{e?.notes||lorem}”</p><span>{e?e.date:'3 Oct · 2:30 pm'} <Icon page="summary" name="imgMaximize"/></span></button></div></section>)}{period==='Today'&&!entries.length&&<p className="card">No entries yet. Add today’s entry to see it here.</p>}<section className="full-summary card"><div className="full-title"><Heading>AI FULL SUMMARY</Heading><button aria-label="Copy summary" onClick={async()=>{try{await navigator.clipboard.writeText(entries.length?entries.map(e=>e.notes||e.symptoms.map(s=>s.name).join(', ')).join('\n'):lorem+' '+lorem+' '+lorem);setModal({title:'Summary copied',body:'The summary is ready to paste.'})}catch{setModal({title:'Copy unavailable',body:'Your browser does not allow clipboard access.'})}}}><Icon page="summary" name="imgVuesaxLinearDocumentCopy"/></button></div><p>{entries.length?entries.map(e=>e.notes||e.symptoms.map(s=>s.name).join(', ')).join(' · '):`${lorem} ${lorem} Lorem ipsum dolor sit amet, consectetur adipiscing elit|`}</p><small>AI draft from your entries · Review before sharing</small><button className="primary compact" onClick={book}>Book Appointment</button></section><Chat/></main>}
 {step>=0&&<main className="content log-content"><div className="steps"><button aria-label="Go back" onClick={()=>go(step===0?'home':step===1?'bleeding':'symptoms')}><Icon page={page} name="imgSvg"/></button><div>{(['bleeding','symptoms','details'] as Page[]).map((p,i)=><button key={p} className={step===i?'active':''} onClick={()=>go(p)} aria-current={step===i?'step':undefined}>STEP {i+1}</button>)}</div></div><div className="log-title"><h1>{['BLEEDING LOG','SYMPTOM SELECTION','TELL US MORE'][step]}</h1><p>{step===2?'Add anything else you’d like to remember':'Select what you felt and how strong it was.'}</p></div>
 {page==='bleeding'&&<><section className="card pad-card"><h3>Your pad size</h3><p>Choose the size you used today</p><div className="pad-options">{['Pantyliner','Regular','Extra-Long Pad','Night Pad','Overnight Panties'].map(p=><button key={p} className={pad===p?'chosen':''} aria-pressed={pad===p} onClick={()=>setPad(p)}>{p}</button>)}</div></section><section className="card flow-card"><h3>Your flow</h3><div className="flow-control"><div className="flow-art"><Icon page="bleeding" name="imgTrack"/><span className="flow-fill" style={{width:`${flow===0?8:flow===1?54:100}%`}}><Icon page="bleeding" name="imgFill"/></span><span className="flow-thumb" style={{left:`${flow===0?7:flow===1?49:93}%`}}><Icon page="bleeding" name="imgThumb"/></span></div><input type="range" min="0" max="2" step="1" value={flow} onChange={e=>setFlow(+e.target.value)} aria-label="Flow amount" aria-valuetext={['Light','Medium','Heavy'][flow]}/><div className="flow-labels">{['Light','Medium','Heavy'].map((s,i)=><span key={s} className={i===flow?'purple':''}>{s}</span>)}</div></div></section><section className="companion card"><Icon page="bleeding" name="imgFriendlyCloud"/><div><p>Let’s log today together</p><small>Every little detail helps you understand your own patterns.</small></div></section><button className="primary" onClick={()=>go('symptoms')}>Continue to Symptoms <Icon page="bleeding" name="imgVuesaxLinearArrowRight"/></button></>}
 {page==='symptoms'&&<>{symptoms.map((s,i)=><section className="card symptom-card" key={i}><div className="symptom-title"><h3>{s.name}</h3><button className={`check ${s.selected?'checked':''}`} aria-label={`${s.selected?'Deselect':'Select'} ${s.name} ${i+1}`} aria-pressed={s.selected} onClick={()=>setSymptoms(a=>a.map((x,j)=>j===i?{...x,selected:!x.selected}:x))}>{s.selected&&<Icon page="symptoms" name="imgImage"/>}</button></div><p>Severity · {s.level} of 5</p><div className="severity">{[1,2,3,4,5].map(n=><button key={n} aria-label={`${s.name} ${i+1} severity ${n}`} aria-pressed={s.selected&&s.level===n} className={s.selected&&s.level===n?'chosen':''} onClick={()=>setSymptoms(a=>a.map((x,j)=>i===j?{...x,level:n,selected:true}:x))}>{n}</button>)}</div><div className="scale"><span>Mild</span><span>Severe</span></div></section>)}<button className="peach" onClick={()=>{setAdding('symptom');setNewName('')}}>+ Add Symptom</button><button className="primary" onClick={()=>go('details')}>Continue to Details <Icon page="symptoms" name="imgVuesaxLinearArrowRight"/></button></>}
 {page==='details'&&<><section className="card notes-card"><h3>Add notes</h3><textarea aria-label="Add notes" placeholder="How was your day? Anything that felt different?" value={notes} onChange={e=>setNotes(e.target.value)}/><small>Optional · Only share what you’re comfortable with</small></section><section className="card meds-card"><h3>Medication &amp; supplements</h3><small>What have you taken today?</small><div className="med-list">{meds.map((m,i)=><button key={i} aria-pressed={m.selected} onClick={()=>setMeds(a=>a.map((x,j)=>i===j?{...x,selected:!x.selected}:x))}><span>{m.name}</span><span className={`check ${m.selected?'checked':''}`}>{m.selected&&<Icon page="details" name="imgImage"/>}</span></button>)}</div><button className="peach" onClick={()=>{setAdding('medication');setNewName('')}}>+ Add new medication</button></section><button className="primary" onClick={save}>Save</button></>}
 </main>}
 <nav className="nav" aria-label="Main navigation"><Icon page={page} name="imgSubtract" className="nav-bg"/><div className="nav-items">{(['home','prepare','create','summary','profile'] as const).map((p,i)=><button key={p} className={`${p==='create'?'create-nav':''} ${page===p||(p==='create'&&step>=0)?'active':''}`} onClick={()=>p==='profile'?setModal({title:'Profile',body:'A Profile screen has not been supplied in this Figma design. Your prototype entries are saved only in this browser.'}):go(p==='create'?'bleeding':p)} aria-current={page===p?'page':undefined}>{p==='create'?<span className="nav-plus"><Icon page={page} name={page==='home'?'imgEllipse105':'imgEllipse104'}/><Icon page={page} className="plus" name={page==='home'?'imgVuesaxLinearAdd1':'imgVuesaxLinearAdd'}/></span>:<Icon page={page} name={['imgVuesaxLinearHome','imgVuesaxLinearEdit2','','imgVuesaxLinearStickynote','imgVuesaxLinearUser'][i]}/>}<span>{p[0].toUpperCase()+p.slice(1)}</span></button>)}</div></nav>
 <dialog ref={dialog} onCancel={()=>{setModal(null);setAdding(null)}} onClick={e=>{if(e.target===dialog.current){setModal(null);setAdding(null)}}}><h2>{adding?`Add ${adding}`:modal?.title}</h2>{adding?<form onSubmit={e=>{e.preventDefault();if(!newName.trim())return;if(adding==='symptom')setSymptoms(a=>[...a,{name:newName.trim(),level:3,selected:true}]);else setMeds(a=>[...a,{name:newName.trim(),selected:true}]);setAdding(null)}}><label>Name<input autoFocus value={newName} onChange={e=>setNewName(e.target.value)} required maxLength={60}/></label><button className="primary">Add</button></form>:<p>{modal?.body}</p>}<button className="peach" onClick={()=>{setModal(null);setAdding(null)}}>Close</button></dialog>
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
